feat: superbase 연동하기
f-lab-edu/strike-deal pull request #10
Opened 2024-12-06 06:47 UTC by limbs722

- superbase database 연동 후 데이터 가져오기

2024-12-06 14:57 UTC, f-lab-jake requested changes

2024-12-06 14:57 UTC, f-lab-jake commented on src/routes/index.tsx
> +    }, []);
페칭로직에 cleanup이 빠져있습니다.
그리고 tanstack query 활용하세요.

2024-12-16 07:49 UTC, f-lab-jake requested changes

2024-12-16 07:49 UTC, f-lab-jake commented on src/api.ts
> +    return data;
요 반복되는 패턴을 함수로 분리해보세요

2025-01-05 12:18 UTC, f-lab-jake requested changes

2025-01-05 12:18 UTC, f-lab-jake commented on src/api.ts
>      }
이 로직을 감싸는 작은 함수를 만들라는 얘기였습니다.

2025-01-05 12:18 UTC, f-lab-jake commented on src/api.ts
>      }
`fetchFromSupabase` 와 같은 함수는 하는일이 너무 많습니다.

2025-01-13 06:40 UTC, limbs722 commented on src/api.ts
>      }
아하 그렇군요.. 다시 만들어보겠습니다..!

2025-01-14 12:41 UTC, f-lab-jake requested changes

2025-01-14 12:41 UTC, f-lab-jake commented on src/api.ts
> +};
이 함수의 타입이 뭔가요?

2025-01-16 08:18 UTC, f-lab-jake requested changes

2025-01-16 08:18 UTC, f-lab-jake commented on src/api.ts
>  };
이 함수는 쓰기가 어렵습니다. 직접 사용해보면서 확인해보세요.

2025-01-17 08:20 UTC, limbs722 commented on src/api.ts
>  };
넵 다시 한번 고민 해보겠습니다!

2025-01-17 08:52 UTC, limbs722 commented on src/api.ts
>  };
수정을 해보았는데 멘토님이 주신 피드백과 맞는 방향인지 잘 모르겠네요... @f-lab-jake

2025-01-19 13:03 UTC, f-lab-jake requested changes

2025-01-19 13:03 UTC, f-lab-jake commented on src/api.ts
>          return error;
throw를 하세요. 그게 왜나은지 생각해보세요.

2025-01-20 07:48 UTC, limbs722 commented on src/api.ts
>          return error;
멘토님 말씀대로 thorw를 사용하니 에러가 발생하면 바로 코드 실행이 중단되기 때문에 에러가 발생한 위치를 알 수 있어 더 용이했습니다. 그리고 코드 실행이 바로 중단됨에 따라 그 이후 코드의 타입 추론도 더 명확하게 할 수 있네요. 더 공부 해야겠지만 많은 깨달음을 얻었습니다. 감사합니다..

2025-01-21 01:16 UTC, f-lab-jake approved these changes

2025-01-22 03:52 UTC, merged