update: 물건 상세 페이지 작업
f-lab-edu/strike-deal pull request #8
Opened 2024-09-10 03:36 UTC by limbs722

- 상세페이지 UI 작업
 - 물건 이미지 carousel 추가
 - 판매글 제목, 가격 표시
 - 좋아요, 조회수, 업데이트 시간 표시

--> 판매 문의하기, 찜하기 버튼 작업 필요

2024-09-12 10:33 UTC, f-lab-jake requested changes

2024-09-12 10:33 UTC, f-lab-jake commented on src/components/products/ImageCarousel.tsx
> +            {images.map((url) => {
가능하면 arrow function쓰세요. cmd + . 으로 쉽게 변환가능합니다.

2024-09-12 10:33 UTC, f-lab-jake commented on src/components/products/ProductDetail.tsx
> +const imgStyle: React.CSSProperties = {
왜 어떤건 emotino쓰고 어떤건 `style`에 직접 넣나요?

2024-09-12 10:33 UTC, f-lab-jake commented on src/utils.ts
> +    }, '');
`reduce` 쓰는걸 피하세요

2024-09-18 06:24 UTC, limbs722 commented on src/components/products/ProductDetail.tsx
> +const imgStyle: React.CSSProperties = {
우선적으로 style에 직접 넣은 다음 emotion으로 모두 정리하려고 했는데 다음부터는 모두 정리한 다음 push 하겠습니다...!!

2024-09-21 00:28 UTC, f-lab-jake requested changes

2024-09-21 00:28 UTC, f-lab-jake commented on src/components/main/TodayRegProductCard.tsx
> +const TodayRegProductCard = ({ product }: { product: TodayRegProductType }) => {
`memo`쓰세요

2024-09-21 00:28 UTC, f-lab-jake commented on src/utils.ts
>  export const getBeautifiedNum = (val: number): string => {
잘 짰습니다. numeral같은 라이브러리를 살펴보세요.

2024-11-08 15:24 UTC, f-lab-jake approved these changes

2024-11-25 08:23 UTC, merged